version: '3.8'

services:
  # 1. Kontainer Utama Aplikasi (PHP-FPM)
  who_app:
    build: .
    container_name: who_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor # Mengunci vendor hasil build agar tidak tertimpa lokal
    networks:
      - app-network

  # 2. Kontainer Nginx Internal Aplikasi
  who_webserver:
    image: nginx:alpine
    container_name: who_webserver
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  # Menggunakan network eksternal yang sama dengan nginx-shared dan mysql-shared
  app-network:
    external: true
